name: dockerhub-push
on:
  push:
    branches: ["main"]
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get secrets from BitWarden
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            1ad85b9c-d534-42e2-b043-b2a601358c41 > DOCKER_USERNAME
            bc2d7021-7cac-4080-a5ba-b2a60135a3e1 > DOCKER_PASSWORD

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: finanssoreal/libreoffice-server:lates
          platforms: linux/amd64, linux/armd64
